import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import Mission from '../components/Mission'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Freshipes</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Banner />

      <Mission />
    </>
  )
}
